apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: kcduk-gameserver-eks
  region: eu-west-1
gitops:
  flux:
    gitProvider: github
    flags:
      owner: fgogolli
      repository: supertuxkart-eks
      branch: kcduk
      namespace: flux-system
      path: deploy/fluxcd/
---
